### ISSUE TITLE
[Feature Req] support for "arbitrary metadata blobs"

### ISSUE THREAD

**Issue by mirochaj** [HERA-Team/pspec_likelihood#52]
It'd be nice if pspec_likelihood could pass around blobs (to steal the lingo used in emcee) in addition to the value of the likelihood. These would be things like the power spectrum itself (to show reconstructions in post-processing) or predictions for independent observables (e.g., UVLFs, tau, etc).

I'm happy to implement this, just curious about how people prefer it to work. The easiest thing to do is just have all the different likelihoods return a tuple containing the likelihood and blobs, which means many other routines need minor modification as well (the discretization functions, `compute_model`, etc). Not terribly elegant, but easy.

Another option could be to allow users to supply the theory model as a class, in which case the computation of the power spectrum goes in a `__call__` method (to preserve current behaviour), and then allow for an optional additional method `compute_blobs` (for example). Then, rather than modifying call sequences all over the place, there could be a single check for the `compute_blobs` function, probably at the end of each `loglike` function -- if found, the function returns `np.sum(loglike), blobs`, if not, it just returns `np.sum(loglike)`, as it does now.

Thoughts @steven-murray @adeliegorce @pagano-michael ?

**Comment by adeliegorce** [comment]
Hey!
What type of blobs did you have in mind bar the sampled models themselves? 
I think your second option is very neat but the potential issue is that when you call `compute_blobs` to obtain the models, you'd have to recompute/redefine a bunch of things that were already included in the `PSpecLikelihood` object via the `DataModelInterface`. 
So maybe it should be two separate things?
- An option in `PSpecLikelihood` allowing you to output the models you've tested in blobs (although if you're fitting cylindrical data we're talking about arrays of shape order (n_iterations, 10^4, 10^3))
- An option based on a `compute_blobs` method as you described in option 2 for other types of outputs that are independent from the properties of the data.

**Comment by steven-murray** [comment]
Thanks @mirochaj, and sorry for the huge delay on replying to this! 

I think the second option is good, but I had kind of planned on people doing that themselves in their scripts, rather than in `pspec_likelihood`. So, eg. your script would be something like (sorry, making this up as I go, so be prepared for errors):

```python
from pspec_likelihood import DataModelInterface, MarginalizedLinearPositiveSystematics

class MyTheory:
   def __call__(self, *args, **kwargs):
       do stuff...

   def compute_blobs(*args, **kwargs):
       return whatever_you_want

my_theory = MyTheory(options)

dmi = DataModelInterface.from_uvpspec(<file>, theory_model=my_theory)
lk = MarginalizedLinearPositiveSystematics(dmi)

def my_likelihood(*args):
    return lk.loglike(*args), my_theory.compute_blobs(*args)

# Now use "my_likelihood" in the emcee sampler....
```

Since this is an easy enough recipe, and means we don't have to know about "blobs" in pspec_likelihood, I think this is a better solution?

**Comment by adeliegorce** [comment]
But in this case, don't you recompute the models every time? rather than directly saving them from inside the likelihood like `blobs` do in `emcee`?

**Comment by steven-murray** [comment]
It depends on what you're doing in `compute_blobs`. This will do one call to `__call__`, to compute the theory, and then one call to `compute_blobs`. If you need or want to use the output of the `__call__` to compute your blobs, you could change the signature of `compute_blobs` to take in the output:

```python

class MyTheory:
   def __call__(self, *args, **kwargs):
       self.model = computed_model
       return self.model

   def compute_blobs(self, *args, **kwargs):
       return 3 * self.model, -self.model, other_funcs(self.model)

def my_likelihood(*args):
    return lk.loglike(*args), my_theory.compute_blobs(*args)
```

**Comment by adeliegorce** [comment]
Nice, thanks for the example!

**Comment by mirochaj** [comment]
OK, so basically write a theory model class that has its own caching system, so rather than relying on pspec_likelihood to pass around blobs, it's smart enough to know not to re-calculate stuff. I'll try to include this approach in an example I'm working on that we can stick in the docs at some point.

**Comment by steven-murray** [comment]
I think this is the best way, but definitely let me know if you have a good motivating counter-example. The one thing to remember is that internally, pspec-likelihood will call the theory function itself, so you just don't want to call that yourself anywhere else. Some docs would be awesome!

**Comment by mirochaj** [comment]
Right, avoiding that second call was what led me down the blobs path to begin with, though I think it can be avoided. Will keep you posted.

**Comment by mirochaj** [comment]
OK, submitted PR #54, which shows an example fit with emcee that uses a `theory_model` class with built-in caching to avoid having to introduce blobs everywhere in pspec_likelihood.

**Comment by steven-murray** [comment]
Done in #54
