### ISSUE TITLE
[BUG] Changing the integration scheme assumes 1D PS even if theory_uses_spherical_k is set to False.

### ISSUE THREAD

**Issue by DanielaBreitman** [HERA-Team/pspec_likelihood#57]
### Description
Changing the integration scheme to one that is not the default is incompatible with cylindrical PS. The PS is assumed to be spherical (see screenshots: 
![Screenshot 1](https://github.com/HERA-Team/pspec_likelihood/assets/39098176/85238f35-80bc-4307-9f52-89dc18c2d1f3)
![Screenshot 2](https://github.com/HERA-Team/pspec_likelihood/assets/39098176/dd9d65d5-fa6f-4401-a863-7479a37a034a)
![Screenshot 3](https://github.com/HERA-Team/pspec_likelihood/assets/39098176/5f2a5838-3062-4cdd-94a9-092d4098cb85)
)

### To Reproduce
1. Create a `DataModelInterface` object with a `theory_model` that returns cylindrical power spectrum with integration scheme that is not the default (`quad` or `trapz`)
2.Run the `discretize_theory` method.

### Expected behavior
No matter the integration scheme during discretization, kperp and kpar should be supplied to the `theory_model` function.

**Comment by steven-murray** [comment]
Thanks @DanielaBreitman for picking this up. Looks like it shouldn't be too hard to solve.
